import Navbar from '@/components/shared/Navbar/Navbar';
import './globals.css';
import Footer from '@/components/shared/Footer/Footer';
export const metadata = {
   title: 'Next.js',
   description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
   return (
      <html lang='en'>
         <body>
            <main className='h-screen'>{children}</main>
         </body>
      </html>
   );
}
